neo4jDatasource:
  uri: bolt://127.0.0.1:7687
  username: neo4j
  password: 123456

kafkaConsumer:
  bootstrap.servers: 192.168.0.106:9092
  group.id: test
  enable.auto.commit: true
  auto.commit.interval.ms: 1000
  key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value.deserializer: org.apache.kafka.common.serialization.StringDeserializer

topic: mysqlsource
kafkaPartitions: 1